[package]
name = "spi-constants"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "1.0"

[lib]
proc-macro = true